version: '3'
services:

  haproxy:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 1936:1936
      - 9000:9000
      - 9001:9001
      - 9002:9002
      - 9003:9003
